---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rca-experiment-runner-serviceaccount
  namespace: rca
imagePullSecrets:
- name: regcred

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rca-experiment-runner-clusterrole
rules:
- apiGroups: ["batch", "chaos-mesh.org", "apps"]
  resources: ["jobs", "networkchaos", "secrets", "deployments"]
  verbs: ["get", "watch", "list", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rca-experiment-runner-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rca-experiment-runner-clusterrole
subjects:
- kind: ServiceAccount
  name: rca-experiment-runner-serviceaccount
  namespace: rca
