apiVersion: batch/v1
kind: Job
metadata:
  name: metrics-processor
spec:
  template:
    spec:
      containers:
      - name: metrics-processor
        image: hexagonbenchmark/metrics-processor:test
        imagePullPolicy: Always
        command: ["./main", "hexagon"]
        envFrom:
        - configMapRef:
            name: metrics-processor-env
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_access_key_id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_secret_access_key
        - name: TZ
          value: "Asia/Tokyo"
      restartPolicy: Never
