apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: experiment

configMapGenerator:
- envs:
  - metrics-processor.env
  name: metrics-processor-env

generatorOptions:
  disableNameSuffixHash: true
